### ISSUE TITLE
Make failed!

### ISSUE THREAD

**Issue by tomjeans** [vkardon/grpc_async_server#1]
>>> Building 'all '...
make[1]: Entering directory '/home/snpe/grpc_async_server/example'
>>> Generating proto files...
mkdir -p ./_generate
../grpc_1.46.6_install/linux/bin/protoc --cpp_out=./_generate --proto_path=. test.proto
>>> Generating proto files...
mkdir -p ./_generate
../grpc_1.46.6_install/linux/bin/protoc --cpp_out=./_generate --proto_path=. health.proto
>>> Generating grpc files...
mkdir -p ./_generate
../grpc_1.46.6_install/linux/bin/protoc --grpc_out=./_generate -I . --plugin=protoc-gen-grpc=../grpc_1.46.6_install/linux/bin/grpc_cpp_plugin test.proto
>>> Generating grpc files...
mkdir -p ./_generate
../grpc_1.46.6_install/linux/bin/protoc --grpc_out=./_generate -I . --plugin=protoc-gen-grpc=../grpc_1.46.6_install/linux/bin/grpc_cpp_plugin health.proto
mkdir -p ./_obj
export LD_LIBRARY_PATH=; g++ -c -MP -MMD -std=c++1z -Wall -pthread -g -I../async_server -I. -I../grpc_1.46.6_install/linux/include -I./_generate -o ./_obj/server.o server.cpp
mkdir -p ./_obj
export LD_LIBRARY_PATH=; g++ -c -MP -MMD -std=c++1z -Wall -pthread -g -I../async_server -I. -I../grpc_1.46.6_install/linux/include -I./_generate -o ./_obj/testServer.o testServer.cpp
mkdir -p ./_obj
export LD_LIBRARY_PATH=; g++ -c -MP -MMD -std=c++1z -Wall -pthread -g -I../async_server -I. -I../grpc_1.46.6_install/linux/include -I./_generate -o ./_obj/testService.o testService.cpp
mkdir -p ./_obj
export LD_LIBRARY_PATH=; g++ -c -MP -MMD -std=c++1z -Wall -pthread -g -I../async_server -I. -I../grpc_1.46.6_install/linux/include -I./_generate -o ./_obj/healthService.o healthService.cpp
mkdir -p ./_obj
export LD_LIBRARY_PATH=; g++ -c -std=c++1z -Wall -pthread -g -I../async_server -I. -I../grpc_1.46.6_install/linux/include -I./_generate -I./_generate -o ./_obj/test.pb.o _generate/test.pb.cc
mkdir -p ./_obj
export LD_LIBRARY_PATH=; g++ -c -std=c++1z -Wall -pthread -g -I../async_server -I. -I../grpc_1.46.6_install/linux/include -I./_generate -I./_generate -o ./_obj/health.pb.o _generate/health.pb.cc
mkdir -p ./_obj
export LD_LIBRARY_PATH=; g++ -c -std=c++1z -Wall -pthread -g -I../async_server -I. -I../grpc_1.46.6_install/linux/include -I./_generate -I./_generate -o ./_obj/test.grpc.pb.o _generate/test.grpc.pb.cc
mkdir -p ./_obj
export LD_LIBRARY_PATH=; g++ -c -std=c++1z -Wall -pthread -g -I../async_server -I. -I../grpc_1.46.6_install/linux/include -I./_generate -I./_generate -o ./_obj/health.grpc.pb.o _generate/health.grpc.pb.cc
export LD_LIBRARY_PATH=; g++  -pthread -o server ./_obj/server.o ./_obj/testServer.o ./_obj/testService.o ./_obj/healthService.o ./_obj/test.pb.o ./_obj/health.pb.o ./_obj/test.grpc.pb.o ./_obj/health.grpc.pb.o -L../grpc_1.46.6_install/linux/lib -L../grpc_1.46.6_install/linux/lib64 -lgrpc -lgrpc++ -lgrpc++_reflection -lgrpc_unsecure -lgrpc++_unsecure -lprotobuf -lcrypto -lssl -lgpr -lz -laddress_sorting -lcares -lre2 -lupb -labsl_synchronization -labsl_raw_logging_internal -labsl_base -labsl_spinlock_wait -labsl_malloc_internal -labsl_time -labsl_time_zone -labsl_int128 -labsl_str_format_internal -labsl_strings -labsl_throw_delegate -labsl_strings_internal -labsl_bad_optional_access -labsl_status -labsl_statusor -labsl_cord -labsl_symbolize -labsl_stacktrace -labsl_debugging_internal -labsl_demangle_internal -labsl_bad_variant_access -labsl_random_internal_randen_slow -labsl_random_internal_randen_hwaes_impl -labsl_random_internal_randen -labsl_random_internal_pool_urbg -labsl_cordz_info -labsl_cord_internal -labsl_cordz_functions -labsl_random_internal_platform -labsl_random_internal_randen_hwaes -labsl_random_internal_seed_material -labsl_random_seed_gen_exception -labsl_cordz_handle -labsl_exponential_biased -labsl_hash -labsl_city -labsl_low_level_hash
./_obj/server.o: In function `gen::GrpcServer::RunImpl(std::vector<gen::AddressUri, std::allocator<gen::AddressUri> > const&, int)':
/home/snpe/grpc_async_server/example/../async_server/grpcServer.hpp:216: undefined reference to `grpc::ServerBuilder::AddListeningPort(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<grpc::ServerCredentials>, int*)'
./_obj/testServer.o: In function `gen::RpcContext::Peer[abi:cxx11]() const':
/home/snpe/grpc_async_server/example/../async_server/grpcContext.hpp:59: undefined reference to `grpc::ServerContextBase::peer[abi:cxx11]() const'
./_obj/testServer.o: In function `grpc::ServerBuilder& grpc::ServerBuilder::AddChannelArgument<int>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int const&)':
/home/snpe/grpc_async_server/example/../grpc_1.46.6_install/linux/include/grpcpp/server_builder.h:241: undefined reference to `grpc::MakeChannelArgumentOption(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
./_obj/testService.o: In function `TestService::Shutdown(gen::RpcContext const&, test::ShutdownRequest const&, test::ShutdownResponse&)':
/home/snpe/grpc_async_server/example/./_generate/test.pb.h:1380: undefined reference to `google::protobuf::internal::ArenaStringPtr::Set(google::protobuf::internal::ArenaStringPtr::EmptyDefault, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::Arena*)'
./_obj/testService.o: In function `TestService::ServerStreamTest(gen::RpcServerStreamContext const&, test::ServerStreamTestRequest const&, test::ServerStreamTestResponse&)':
/home/snpe/grpc_async_server/example/./_generate/test.pb.h:1518: undefined reference to `google::protobuf::internal::ArenaStringPtr::Set(google::protobuf::internal::ArenaStringPtr::EmptyDefault, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, google::protobuf::Arena*)'
./_obj/test.pb.o: In function `test::ShutdownRequest::ShutdownRequest(test::ShutdownRequest const&)':
/home/snpe/grpc_async_server/example/_generate/test.pb.cc:259: undefined reference to `google::protobuf::internal::ArenaStringPtr::Set(google::protobuf::internal::ArenaStringPtr::EmptyDefault, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::Arena*)'
./_obj/test.pb.o: In function `test::ShutdownRequest::_InternalParse(char const*, google::protobuf::internal::ParseContext*)':
/home/snpe/grpc_async_server/example/_generate/test.pb.cc:314: undefined reference to `google::protobuf::internal::InlineGreedyStringParser(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, char const*, google::protobuf::internal::ParseContext*)'
./_obj/test.pb.o: In function `test::ShutdownRequest::MergeFrom(test::ShutdownRequest const&)':
/home/snpe/grpc_async_server/example/_generate/test.pb.h:1318: undefined reference to `google::protobuf::internal::ArenaStringPtr::Set(google::protobuf::internal::ArenaStringPtr::EmptyDefault, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::Arena*)'
./_obj/test.pb.o: In function `test::ShutdownResponse::ShutdownResponse(test::ShutdownResponse const&)':
/home/snpe/grpc_async_server/example/_generate/test.pb.cc:462: undefined reference to `google::protobuf::internal::ArenaStringPtr::Set(google::protobuf::internal::ArenaStringPtr::EmptyDefault, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::Arena*)'
./_obj/test.pb.o: In function `test::ShutdownResponse::_InternalParse(char const*, google::protobuf::internal::ParseContext*)':
/home/snpe/grpc_async_server/example/_generate/test.pb.cc:528: undefined reference to `google::protobuf::internal::InlineGreedyStringParser(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, char const*, google::protobuf::internal::ParseContext*)'
./_obj/test.pb.o: In function `test::ShutdownResponse::MergeFrom(test::ShutdownResponse const&)':
/home/snpe/grpc_async_server/example/_generate/test.pb.h:1393: undefined reference to `google::protobuf::internal::ArenaStringPtr::Set(google::protobuf::internal::ArenaStringPtr::EmptyDefault, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::Arena*)'
./_obj/test.pb.o: In function `test::ServerStreamTestRequest::ServerStreamTestRequest(test::ServerStreamTestRequest const&)':
/home/snpe/grpc_async_server/example/_generate/test.pb.cc:908: undefined reference to `google::protobuf::internal::ArenaStringPtr::Set(google::protobuf::internal::ArenaStringPtr::EmptyDefault, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::Arena*)'
./_obj/test.pb.o: In function `test::ServerStreamTestRequest::_InternalParse(char const*, google::protobuf::internal::ParseContext*)':
/home/snpe/grpc_async_server/example/_generate/test.pb.cc:963: undefined reference to `google::protobuf::internal::InlineGreedyStringParser(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, char const*, google::protobuf::internal::ParseContext*)'
./_obj/test.pb.o: In function `test::ServerStreamTestRequest::MergeFrom(test::ServerStreamTestRequest const&)':
/home/snpe/grpc_async_server/example/_generate/test.pb.h:1476: undefined reference to `google::protobuf::internal::ArenaStringPtr::Set(google::protobuf::internal::ArenaStringPtr::EmptyDefault, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::Arena*)'
./_obj/test.pb.o: In function `test::ServerStreamTestResponse::ServerStreamTestResponse(test::ServerStreamTestResponse const&)':
/home/snpe/grpc_async_server/example/_generate/test.pb.cc:1111: undefined reference to `google::protobuf::internal::ArenaStringPtr::Set(google::protobuf::internal::ArenaStringPtr::EmptyDefault, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::Arena*)'
./_obj/test.pb.o: In function `test::ServerStreamTestResponse::_InternalParse(char const*, google::protobuf::internal::ParseContext*)':
/home/snpe/grpc_async_server/example/_generate/test.pb.cc:1169: undefined reference to `google::protobuf::internal::InlineGreedyStringParser(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, char const*, google::protobuf::internal::ParseContext*)'
./_obj/test.pb.o: In function `test::ServerStreamTestResponse::MergeFrom(test::ServerStreamTestResponse const&)':
/home/snpe/grpc_async_server/example/_generate/test.pb.h:1531: undefined reference to `google::protobuf::internal::ArenaStringPtr::Set(google::protobuf::internal::ArenaStringPtr::EmptyDefault, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::Arena*)'
./_obj/test.pb.o: In function `test::ClientStreamTestRequest::ClientStreamTestRequest(test::ClientStreamTestRequest const&)':
/home/snpe/grpc_async_server/example/_generate/test.pb.cc:1340: undefined reference to `google::protobuf::internal::ArenaStringPtr::Set(google::protobuf::internal::ArenaStringPtr::EmptyDefault, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::Arena*)'
./_obj/test.pb.o: In function `test::ClientStreamTestRequest::_InternalParse(char const*, google::protobuf::internal::ParseContext*)':
/home/snpe/grpc_async_server/example/_generate/test.pb.cc:1395: undefined reference to `google::protobuf::internal::InlineGreedyStringParser(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, char const*, google::protobuf::internal::ParseContext*)'
./_obj/test.pb.o: In function `test::ClientStreamTestRequest::MergeFrom(test::ClientStreamTestRequest const&)':
/home/snpe/grpc_async_server/example/_generate/test.pb.h:1606: undefined reference to `google::protobuf::internal::ArenaStringPtr::Set(google::protobuf::internal::ArenaStringPtr::EmptyDefault, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::Arena*)'
./_obj/test.pb.o: In function `google::protobuf::io::EpsCopyOutputStream::WriteStringMaybeAliased(unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)':
/home/snpe/grpc_async_server/example/../grpc_1.46.6_install/linux/include/google/protobuf/io/coded_stream.h:733: undefined reference to `google::protobuf::io::EpsCopyOutputStream::WriteStringMaybeAliasedOutline(unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char*)'
./_obj/test.pb.o: In function `google::protobuf::internal::GetEmptyStringAlreadyInited[abi:cxx11]()':
/home/snpe/grpc_async_server/example/../grpc_1.46.6_install/linux/include/google/protobuf/message_lite.h:139: undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
./_obj/test.pb.o: In function `test::ShutdownRequest::_internal_mutable_reason[abi:cxx11]()':
/home/snpe/grpc_async_server/example/_generate/test.pb.h:1322: undefined reference to `google::protobuf::internal::ArenaStringPtr::Mutable[abi:cxx11](google::protobuf::internal::ArenaStringPtr::EmptyDefault, google::protobuf::Arena*)'
./_obj/test.pb.o: In function `test::ShutdownResponse::_internal_mutable_msg[abi:cxx11]()':
/home/snpe/grpc_async_server/example/_generate/test.pb.h:1397: undefined reference to `google::protobuf::internal::ArenaStringPtr::Mutable[abi:cxx11](google::protobuf::internal::ArenaStringPtr::EmptyDefault, google::protobuf::Arena*)'
./_obj/test.pb.o: In function `test::ServerStreamTestRequest::_internal_mutable_msg[abi:cxx11]()':
/home/snpe/grpc_async_server/example/_generate/test.pb.h:1480: undefined reference to `google::protobuf::internal::ArenaStringPtr::Mutable[abi:cxx11](google::protobuf::internal::ArenaStringPtr::EmptyDefault, google::protobuf::Arena*)'
./_obj/test.pb.o: In function `test::ServerStreamTestResponse::_internal_mutable_msg[abi:cxx11]()':
/home/snpe/grpc_async_server/example/_generate/test.pb.h:1535: undefined reference to `google::protobuf::internal::ArenaStringPtr::Mutable[abi:cxx11](google::protobuf::internal::ArenaStringPtr::EmptyDefault, google::protobuf::Arena*)'
./_obj/test.pb.o: In function `test::ClientStreamTestRequest::_internal_mutable_msg[abi:cxx11]()':
/home/snpe/grpc_async_server/example/_generate/test.pb.h:1610: undefined reference to `google::protobuf::internal::ArenaStringPtr::Mutable[abi:cxx11](google::protobuf::internal::ArenaStringPtr::EmptyDefault, google::protobuf::Arena*)'
./_obj/test.pb.o: In function `test::ShutdownRequest::ShutdownRequest(google::protobuf::internal::ConstantInitialized)':
/home/snpe/grpc_async_server/example/_generate/test.pb.cc:22: undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
./_obj/test.pb.o: In function `test::ShutdownResponse::ShutdownResponse(google::protobuf::internal::ConstantInitialized)':
/home/snpe/grpc_async_server/example/_generate/test.pb.cc:35: undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
./_obj/test.pb.o: In function `test::ServerStreamTestRequest::ServerStreamTestRequest(google::protobuf::internal::ConstantInitialized)':
/home/snpe/grpc_async_server/example/_generate/test.pb.cc:70: undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
./_obj/test.pb.o: In function `test::ServerStreamTestResponse::ServerStreamTestResponse(google::protobuf::internal::ConstantInitialized)':
/home/snpe/grpc_async_server/example/_generate/test.pb.cc:83: undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
./_obj/test.pb.o: In function `test::ClientStreamTestRequest::ClientStreamTestRequest(google::protobuf::internal::ConstantInitialized)':
/home/snpe/grpc_async_server/example/_generate/test.pb.cc:95: undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
./_obj/test.pb.o:(.data.rel.ro._ZTVN4test24ClientStreamTestResponseE[_ZTVN4test24ClientStreamTestResponseE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
./_obj/test.pb.o:(.data.rel.ro._ZTVN4test24ClientStreamTestResponseE[_ZTVN4test24ClientStreamTestResponseE]+0x40): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
./_obj/test.pb.o:(.data.rel.ro._ZTVN4test23ClientStreamTestRequestE[_ZTVN4test23ClientStreamTestRequestE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
./_obj/test.pb.o:(.data.rel.ro._ZTVN4test23ClientStreamTestRequestE[_ZTVN4test23ClientStreamTestRequestE]+0x40): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
./_obj/test.pb.o:(.data.rel.ro._ZTVN4test24ServerStreamTestResponseE[_ZTVN4test24ServerStreamTestResponseE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
./_obj/test.pb.o:(.data.rel.ro._ZTVN4test24ServerStreamTestResponseE[_ZTVN4test24ServerStreamTestResponseE]+0x40): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
./_obj/test.pb.o:(.data.rel.ro._ZTVN4test23ServerStreamTestRequestE[_ZTVN4test23ServerStreamTestRequestE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
./_obj/test.pb.o:(.data.rel.ro._ZTVN4test23ServerStreamTestRequestE[_ZTVN4test23ServerStreamTestRequestE]+0x40): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
./_obj/test.pb.o:(.data.rel.ro._ZTVN4test12PingResponseE[_ZTVN4test12PingResponseE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
./_obj/test.pb.o:(.data.rel.ro._ZTVN4test12PingResponseE[_ZTVN4test12PingResponseE]+0x40): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
./_obj/test.pb.o:(.data.rel.ro._ZTVN4test11PingRequestE[_ZTVN4test11PingRequestE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
./_obj/test.pb.o:(.data.rel.ro._ZTVN4test11PingRequestE[_ZTVN4test11PingRequestE]+0x40): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
./_obj/test.pb.o:(.data.rel.ro._ZTVN4test16ShutdownResponseE[_ZTVN4test16ShutdownResponseE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
./_obj/test.pb.o:(.data.rel.ro._ZTVN4test16ShutdownResponseE[_ZTVN4test16ShutdownResponseE]+0x40): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
./_obj/test.pb.o:(.data.rel.ro._ZTVN4test15ShutdownRequestE[_ZTVN4test15ShutdownRequestE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
./_obj/test.pb.o:(.data.rel.ro._ZTVN4test15ShutdownRequestE[_ZTVN4test15ShutdownRequestE]+0x40): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
./_obj/health.pb.o: In function `grpc::health::v1::HealthCheckRequest::HealthCheckRequest(grpc::health::v1::HealthCheckRequest const&)':
/home/snpe/grpc_async_server/example/_generate/health.pb.cc:161: undefined reference to `google::protobuf::internal::ArenaStringPtr::Set(google::protobuf::internal::ArenaStringPtr::EmptyDefault, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::Arena*)'
./_obj/health.pb.o: In function `grpc::health::v1::HealthCheckRequest::_InternalParse(char const*, google::protobuf::internal::ParseContext*)':
/home/snpe/grpc_async_server/example/_generate/health.pb.cc:216: undefined reference to `google::protobuf::internal::InlineGreedyStringParser(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, char const*, google::protobuf::internal::ParseContext*)'
./_obj/health.pb.o: In function `grpc::health::v1::HealthCheckRequest::MergeFrom(grpc::health::v1::HealthCheckRequest const&)':
/home/snpe/grpc_async_server/example/_generate/health.pb.h:471: undefined reference to `google::protobuf::internal::ArenaStringPtr::Set(google::protobuf::internal::ArenaStringPtr::EmptyDefault, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::Arena*)'
./_obj/health.pb.o: In function `grpc::health::v1::HealthCheckRequest::_internal_mutable_service[abi:cxx11]()':
/home/snpe/grpc_async_server/example/_generate/health.pb.h:475: undefined reference to `google::protobuf::internal::ArenaStringPtr::Mutable[abi:cxx11](google::protobuf::internal::ArenaStringPtr::EmptyDefault, google::protobuf::Arena*)'
./_obj/health.pb.o: In function `grpc::health::v1::HealthCheckRequest::HealthCheckRequest(google::protobuf::internal::ConstantInitialized)':
/home/snpe/grpc_async_server/example/_generate/health.pb.cc:24: undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
./_obj/health.pb.o:(.data.rel.ro._ZTVN4grpc6health2v119HealthCheckResponseE[_ZTVN4grpc6health2v119HealthCheckResponseE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
./_obj/health.pb.o:(.data.rel.ro._ZTVN4grpc6health2v119HealthCheckResponseE[_ZTVN4grpc6health2v119HealthCheckResponseE]+0x40): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
./_obj/health.pb.o:(.data.rel.ro._ZTVN4grpc6health2v118HealthCheckRequestE[_ZTVN4grpc6health2v118HealthCheckRequestE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName[abi:cxx11]() const'
./_obj/health.pb.o:(.data.rel.ro._ZTVN4grpc6health2v118HealthCheckRequestE[_ZTVN4grpc6health2v118HealthCheckRequestE]+0x40): undefined reference to `google::protobuf::Message::InitializationErrorString[abi:cxx11]() const'
collect2: error: ld returned 1 exit status
Makefile:143: recipe for target 'server' failed
make[1]: *** [server] Error 1
make[1]: Leaving directory '/home/snpe/grpc_async_server/example'
Makefile:10: recipe for target 'all' failed
make: *** [all] Error 2
How to solve this? Thanks

**Comment by vkardon** [comment]
Hey...I'm using static linking for gRpc libs in my build. It means *.a libs in this repository wouldn't not link for you unless you use the same version of gcc compiler. You can build your own set of static gRpc libs, that would work, or you can change Makefile to use shared libs. One more thing - you will need g++ (or other compiler) that supports C++17.

**Comment by vkardon** [comment]
Update: I just pushed a fix for Makefile.shared and made it default for a build. It should fix that build issue.
